project:
  type: website
  output-dir: docs

website:
  title: "Ben Matthews blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/benmatthewsed
      - icon: twitter
        href: https://twitter.com/benmatthewsed
format:
  html:
    theme: cosmo
    css: styles.css



