project:
  type: website
  output-dir: docs

website:
  title: "Ben Matthews"
  navbar:
  
      # my sub-pages
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Presentations"
        href: presentations/index.qmd
      - text: "Posts"
        href: posts/index.qmd
      - text: "Training"
        href: training/index.qmd
        

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

