---
title: "Presentations"
---

- [What to do with an odds ratio of 35?](https://benmatthewsed.github.io/what_to_do_odds_ratios) With matched case-control data (e.g. matching each 'case' of your outcome to three 'controls'), researchers are recommended to fit conditional logistic regression models to account for the structure of this matching in their analysis. However, this means that by default you can't calculate meaningful marginal effects or predicted probabilities from your model - because the model's intercept is determined by the ratio of cases to controls. This leaves you to focus on odds ratios... but what if you (or your audience) don't like the odds ratios you get? Using an example from ongoing analysis from the [Policing the Pandemic in Scotland](https://www.law.ed.ac.uk/research/research-projects/policing-the-pandemic) project, in this presentation I will talk through our thought process in figuring out what we can do with some odds ratios we don't really like, and end up asking what is a marginal effect anyway?

- [The Age-crime curve in (some of) Northern Europe](https://benmatthewsed.github.io/age_crime_curve_europe/age_crime_curve_europe.html#/title-slide)
- [Understanding the relationships between risk factors, intersectional identities and criminal career trajectories: A multilevel approach](https://benmatthewsed.github.io/qstep-nov-2020-exeter/#1)

